// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Message struct {
	ID        string
	SessionID string
	CreatedAt int64
	UpdatedAt int64
	Data      string
}

type Part struct {
	ID        string
	MessageID string
	SessionID string
	CreatedAt int64
	UpdatedAt int64
	Data      string
}

type Session struct {
	ID        string
	ProjectID string
	Slug      string
	Directory string
	Title     string
	CreatedAt int64
	UpdatedAt int64
}
